grafana:
  enabled: true
  version: "7.0.21"
  adminUser: admin
  adminPassword: strongpassword

loki:
  enabled: true
  version: "5.41.4"
  loki:
    commonConfig:
      replication_factor: 1
      storage:
        type: 'filesystem'
    readinessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 45
    livenessProbe:
      httpGet:
        path: /ready
        port: http-metrics
    initialDelaySeconds: 45
  test:
    enabled: false
  gateway:
    enabled: false
  singleBinary:
    replicas: 1
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false

promtail:
  enabled: true
  version: "6.15.3"
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://grafana-stack-loki:3100/loki/api/v1/push

tempo:
  enabled: true
  version: "1.7.1"

prometheus:
  enabled: true
  version: "25.8.2"