grafana:
  enabled: true
  version: "7.0.21"
  adminUser: admin
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://grafana-stack-kube-prometh-prometheus.monitoring.svc.cluster.local:9090/
        jsonData:
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 2.48.1
          cacheLevel: 'Medium'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
      - name: Loki
        type: loki
        access: proxy
        url: http://grafana-stack-loki.monitoring.svc.cluster.local:3100/
        jsonData:
          maxLines: 1000
      - name: Tempo
        type: tempo
        access: proxy
        url: http://grafana-stack-tempo.monitoring.svc.cluster.local:3100/


loki:
  enabled: true
  version: "5.41.4"
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
      storage:
        type: 'filesystem'
    readinessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 45
    livenessProbe:
      httpGet:
        path: /ready
        port: http-metrics
    initialDelaySeconds: 45
  test:
    enabled: false
  gateway:
    enabled: false
  singleBinary:
    replicas: 1
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false

promtail:
  enabled: true
  version: "6.15.3"
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://grafana-stack-loki:3100/loki/api/v1/push

tempo:
  enabled: true
  version: "1.7.1"

kube-prometheus:
  enabled: true
  version: "8.23.3"
  prometheus:
    thanos:
      create: true

thanos:
  enabled: true
  version: "12.20.3"
  storegateway:
    enabled: false